### ISSUE TITLE
Information flow - really small remark

### ISSUE THREAD

**Issue by LeonieHagitte** [brandmaier/reproducibleRchunks-manuscript#1]
I had trouble connecting the sentence in line 79 :"This is particularly interesting for psychological research reports, as the `papaja` package [@R-papaja] allows R Markdown documents (including tables and figures) to be automatically formatted in APA style; most importantly, statistical results and content of tables and figures are dynamically generated." to the first paragraph. To me this feels bit disconnected and left me with the question, why do I need to know this? As an example for relevance, I would have understood it maybe a bit further down the argument, somewhat like, ... because in psychological research, many are working with R markdown( for reasons x,y,z), this is especially relevant for them. ... ?

**Comment by brandmaier** [comment]
Well spotted... I tried to sneak this in somewhere to speak to a Psych audience but I guess the audience of the paper is much larger :-) I will change this.
