### ISSUE TITLE
Small question

### ISSUE THREAD

**Issue by LeonieHagitte** [brandmaier/reproducibleRchunks-manuscript#2]
In lines 110 and 111 I wondered, what implications does that have, so in the text below it is highlighted, that if changes are made in the non-reproducible part, thus the definition of variable x, this would show in the comparison of the computational results in the reproducible sum. What I wondered is, why wouldn't I then make the variable definition in a reproducible chunk as well? wouldn't that prevent the variable definition from deviating?

**Comment by brandmaier** [comment]
Absolutely, it would make sense to have all of this in a reproducibleR chunk.

**Comment by brandmaier** [comment]
The revised version contains more information on why one would not test everything for exact reproducibility.
