### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LeonieHagitte** [brandmaier/reproducibleRchunks-manuscript#3]
In this section 189-191: In addition to the contents of all newly declared variables in a `reproducibleR`-chunk, the package also stores a fingerprint of the code syntax.
This allows later checks whether a potential non-reproduction is due to a modification of the code chunk since the original computation. The storage of the fingerprinted information about a code chunk and its computational results is illustrated in the schematic in Figure \@ref(fig:jsonschema).

Is that to a systematic placement/ representation of the position in the hexadecimal string? For me an example or a few of them would help understanding. I imagine it like in the string different numbers or letters will change, if there are inconsistencies in the code vs if there are inconsistencies in the results etc. - maybe an example could highlight this?

**Comment by brandmaier** [comment]
Correct.
