### ISSUE TITLE
numbers vs numbers_ex

### ISSUE THREAD

**Issue by LeonieHagitte** [brandmaier/reproducibleRchunks-manuscript#4]
Had to read this a few times.

Here is an example of how the contents of a single variable called `numbers` is stored in JSON format. Here, the variable content is a vector of five random draws from the number one to ten: `r numbers_ex` generated by the following command:

```{r echo=TRUE, eval=FALSE}
numbers_ex <- sample(1:10, 5)
```

At first I stumbled over it, because I expected to see the definition of the variable "numbers" and then it seemed inconsistent. Maybe one could give also a variable definition? Or just refer to the vector? 

Also This is inconsistent with the pdf version, you sent me, as There it is the following text, where "numbers_ex" is not explicitly mentioned: 

Here is an example of how the contents of a single variable called numbers is stored in
JSON format. Here, the variable content is a vector of five random draws from the number
one to ten: 1, 5, 10, 8, and 2 generated by the following command:
```{r echo=TRUE, eval=FALSE}
numbers_ex <- sample(1:10, 5)
```

**Comment by brandmaier** [comment]
Thanks! It is `numbers` now not `numbers_ex`.
